// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
#define EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
