// generated from rosidl_typesupport_introspection_c/resource/srv__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__INTROSPECTION_TYPE_SUPPORT_H_
#define EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/service_type_support.h>

#include "example_interfaces/msg/rosidl_generator_c__visibility_control.h"

static rosidl_service_type_support_t example_interfaces__srv__rosidl_typesupport_introspection_c__AddTwoInts_service_type_support_handle;

#endif  // EXAMPLE_INTERFACES__SRV__ADD_TWO_INTS__INTROSPECTION_TYPE_SUPPORT_H_
