// generated from rosidl_typesupport_introspection_c/resource/srv__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef DIAGNOSTIC_MSGS__SRV__SELF_TEST__INTROSPECTION_TYPE_SUPPORT_H_
#define DIAGNOSTIC_MSGS__SRV__SELF_TEST__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/service_type_support.h>

#include "diagnostic_msgs/msg/rosidl_generator_c__visibility_control.h"

static rosidl_service_type_support_t diagnostic_msgs__srv__rosidl_typesupport_introspection_c__SelfTest_service_type_support_handle;

#endif  // DIAGNOSTIC_MSGS__SRV__SELF_TEST__INTROSPECTION_TYPE_SUPPORT_H_
