// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef DIAGNOSTIC_MSGS__SRV__SELF_TEST__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
#define DIAGNOSTIC_MSGS__SRV__SELF_TEST__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // DIAGNOSTIC_MSGS__SRV__SELF_TEST__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
