// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef VISUALIZATION_MSGS__MSG__INTERACTIVE_MARKER_FEEDBACK__INTROSPECTION_TYPE_SUPPORT_H_
#define VISUALIZATION_MSGS__MSG__INTERACTIVE_MARKER_FEEDBACK__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // VISUALIZATION_MSGS__MSG__INTERACTIVE_MARKER_FEEDBACK__INTROSPECTION_TYPE_SUPPORT_H_
