// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef LIFECYCLE_MSGS__SRV__GET_STATE__RESPONSE__INTROSPECTION_TYPE_SUPPORT_H_
#define LIFECYCLE_MSGS__SRV__GET_STATE__RESPONSE__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // LIFECYCLE_MSGS__SRV__GET_STATE__RESPONSE__INTROSPECTION_TYPE_SUPPORT_H_
