// generated from rosidl_typesupport_introspection_c/resource/srv__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef COMPOSITION__SRV__LOAD_NODE__INTROSPECTION_TYPE_SUPPORT_H_
#define COMPOSITION__SRV__LOAD_NODE__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/service_type_support.h>

#include "composition/msg/rosidl_generator_c__visibility_control.h"

static rosidl_service_type_support_t composition__srv__rosidl_typesupport_introspection_c__LoadNode_service_type_support_handle;

#endif  // COMPOSITION__SRV__LOAD_NODE__INTROSPECTION_TYPE_SUPPORT_H_
