// generated from rosidl_typesupport_introspection_c/resource/msg__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef COMPOSITION__SRV__LOAD_NODE__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
#define COMPOSITION__SRV__LOAD_NODE__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/message_type_support.h>

#endif  // COMPOSITION__SRV__LOAD_NODE__REQUEST__INTROSPECTION_TYPE_SUPPORT_H_
