// generated from rosidl_typesupport_introspection_c/resource/srv__introspection_type_support.h.em
// generated code does not contain a copyright notice

#ifndef NAV_MSGS__SRV__GET_PLAN__INTROSPECTION_TYPE_SUPPORT_H_
#define NAV_MSGS__SRV__GET_PLAN__INTROSPECTION_TYPE_SUPPORT_H_

#include <rosidl_generator_c/service_type_support.h>

#include "nav_msgs/msg/rosidl_generator_c__visibility_control.h"

static rosidl_service_type_support_t nav_msgs__srv__rosidl_typesupport_introspection_c__GetPlan_service_type_support_handle;

#endif  // NAV_MSGS__SRV__GET_PLAN__INTROSPECTION_TYPE_SUPPORT_H_
